<h1> Importing Libraries </h1>

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import preprocessing

<h1> Downloading the dataset </h1>

In [4]:
!wget -O seattle-data-collision.csv https://amapplied-data-science-capstone.s3.us-east.cloud-object-storage.appdomain.cloud/Full%20Data%20Collisions.csv

--2020-08-30 22:17:20--  https://amapplied-data-science-capstone.s3.us-east.cloud-object-storage.appdomain.cloud/Full%20Data%20Collisions.csv
Resolving amapplied-data-science-capstone.s3.us-east.cloud-object-storage.appdomain.cloud (amapplied-data-science-capstone.s3.us-east.cloud-object-storage.appdomain.cloud)... 169.63.118.98
Connecting to amapplied-data-science-capstone.s3.us-east.cloud-object-storage.appdomain.cloud (amapplied-data-science-capstone.s3.us-east.cloud-object-storage.appdomain.cloud)|169.63.118.98|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 84554087 (81M) [text/csv]
Saving to: ‘seattle-data-collision.csv’

100%[======================================>] 84,554,087  95.6MB/s   in 0.8s

2020-08-30 22:17:21 (95.6 MB/s) - ‘seattle-data-collision.csv’ saved [84554087/84554087]

<h1> Understanding the Data </h1>

In [5]:
df = pd.read_csv('seattle-data-collision.csv')
df.shape

(221006, 40)

In [6]:
df.head()

,X,Y,OBJECTID,INCKEY,COLDETKEY,REPORTNO,STATUS,ADDRTYPE,INTKEY,LOCATION,...,ROADCOND,LIGHTCOND,PEDROWNOTGRNT,SDOTCOLNUM,SPEEDING,ST_COLCODE,ST_COLDESC,SEGLANEKEY,CROSSWALKKEY,HITPARKEDCAR
0,1.268969e+06,231759.927713,1,333240,334740,3851889,Unmatched,Intersection,28743.0,9TH AVE N AND ROY ST,...,NaN,NaN,NaN,NaN,NaN,,NaN,0,0,N
1,1.271618e+06,202779.935236,2,333317,334817,3834541,Unmatched,Block,NaN,S MICHIGAN ST BETWEEN 5TH PL S AND 6TH AVE S,...,NaN,NaN,NaN,NaN,NaN,,NaN,0,0,N
2,1.271322e+06,217404.090003,3,1367,1367,3671783,Matched,Intersection,31348.0,4TH AVE S AND S HOLGATE ST,...,Dry,Daylight,NaN,NaN,NaN,13,From same direction - both going straight - bo...,0,0,N
3,1.269294e+06,224852.790938,4,1189,1189,3548948,Matched,Block,NaN,1ST AVE BETWEEN SENECA ST AND UNIVERSITY ST,...,Dry,Daylight,NaN,NaN,NaN,11,From same direction - both going straight - bo...,0,0,N
4,1.259501e+06,255054.109113,5,30400,30400,04046023,Unmatched,Intersection,23863.0,18TH AVE NW AND NW 83RD ST,...,NaN,NaN,NaN,4046023.0,NaN,NaN,NaN,0,0,N

<h2> Checking all columns for Missing Values </h2>

In [7]:
missing_data=df.isnull()
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

X
False    213539
True       7467
Name: X, dtype: int64

Y
False    213539
True       7467
Name: Y, dtype: int64

OBJECTID
False    221006
Name: OBJECTID, dtype: int64

INCKEY
False    221006
Name: INCKEY, dtype: int64

COLDETKEY
False    221006
Name: COLDETKEY, dtype: int64

REPORTNO
False    221006
Name: REPORTNO, dtype: int64

STATUS
False    221006
Name: STATUS, dtype: int64

ADDRTYPE
False    217295
True       3711
Name: ADDRTYPE, dtype: int64

INTKEY
True     149278
False     71728
Name: INTKEY, dtype: int64

LOCATION
False    216422
True       4584
Name: LOCATION, dtype: int64

EXCEPTRSNCODE
True     120403
False    100603
Name: EXCEPTRSNCODE, dtype: int64

EXCEPTRSNDESC
True     209237
False     11769
Name: EXCEPTRSNDESC, dtype: int64

SEVERITYCODE
False    221005
True          1
Name: SEVERITYCODE, dtype: int64

SEVERITYDESC
False    221006
Name: SEVERITYDESC, dtype: int64

COLLISIONTYPE
False    194678
True      26328
Name: COLLISIONTYPE, dtype: int64

PERSONCOUNT
False    221006
Name: PERSONCOUNT, dtype: int64

PEDCOUNT
False    221006
Name: PEDCOUNT, dtype: int64

PEDCYLCOUNT
False    221006
Name: PEDCYLCOUNT, dtype: int64

VEHCOUNT
False    221006
Name: VEHCOUNT, dtype: int64

INJURIES
False    221006
Name: INJURIES, dtype: int64

SERIOUSINJURIES
False    221006
Name: SERIOUSINJURIES, dtype: int64

FATALITIES
False    221006
Name: FATALITIES, dtype: int64

INCDATE
False    221006
Name: INCDATE, dtype: int64

INCDTTM
False    221006
Name: INCDTTM, dtype: int64

JUNCTIONTYPE
False    209046
True      11960
Name: JUNCTIONTYPE, dtype: int64

SDOT_COLCODE
False    221005
True          1
Name: SDOT_COLCODE, dtype: int64

SDOT_COLDESC
False    221005
True          1
Name: SDOT_COLDESC, dtype: int64

INATTENTIONIND
True     190818
False     30188
Name: INATTENTIONIND, dtype: int64

UNDERINFL
False    194698
True      26308
Name: UNDERINFL, dtype: int64

WEATHER
False    194489
True      26517
Name: WEATHER, dtype: int64

ROADCOND
False    194569
True      26437
Name: ROADCOND, dtype: int64

LIGHTCOND
False    194401
True      26605
Name: LIGHTCOND, dtype: int64

PEDROWNOTGRNT
True     215819
False      5187
Name: PEDROWNOTGRNT, dtype: int64

SDOTCOLNUM
False    127205
True      93801
Name: SDOTCOLNUM, dtype: int64

SPEEDING
True     211106
False      9900
Name: SPEEDING, dtype: int64

ST_COLCODE
False    211593
True       9413
Name: ST_COLCODE, dtype: int64

ST_COLDESC
False    194678
True      26328
Name: ST_COLDESC, dtype: int64

SEGLANEKEY
False    221006
Name: SEGLANEKEY, dtype: int64

CROSSWALKKEY
False    221006
Name: CROSSWALKKEY, dtype: int64

HITPARKEDCAR
False    221006
Name: HITPARKEDCAR, dtype: int64

#### Cleaning Data for columns with no relevant usage

Drop columns X, Y, OBJECTID, INCKEY, COLDETKEY, REPORTNO, EXCEPTRSNCODE, EXCEPTRSNDESC, SEGLANEKEY, CROSSWALKKEY, INCDTTM, SDOTCOLNUM, ST_COLCODE, ST_COLDESC, HITPARKEDCAR, SDOT_COLDESC, SDOT_COLCODE, LOCATION, INTKEY as these are primary key columns and are not providing any new information for the algorithm

In [8]:
df.drop(['X','Y','OBJECTID','INCKEY','COLDETKEY','REPORTNO','EXCEPTRSNCODE','EXCEPTRSNDESC','SEGLANEKEY','CROSSWALKKEY',
         'INCDTTM','SDOTCOLNUM','ST_COLCODE','ST_COLDESC','HITPARKEDCAR','SDOT_COLDESC','SDOT_COLCODE','LOCATION','INTKEY'], axis=1, inplace=True)

In [9]:
df.head()

,STATUS,ADDRTYPE,SEVERITYCODE,SEVERITYDESC,COLLISIONTYPE,PERSONCOUNT,PEDCOUNT,PEDCYLCOUNT,VEHCOUNT,INJURIES,...,FATALITIES,INCDATE,JUNCTIONTYPE,INATTENTIONIND,UNDERINFL,WEATHER,ROADCOND,LIGHTCOND,PEDROWNOTGRNT,SPEEDING
0,Unmatched,Intersection,2,Injury Collision,NaN,2,0,0,0,2,...,0,2020/08/10 00:00:00+00,At Intersection (intersection related),NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Unmatched,Block,2,Injury Collision,NaN,3,0,0,0,1,...,0,2020/08/14 00:00:00+00,Mid-Block (not related to intersection),NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Matched,Intersection,1,Property Damage Only Collision,Rear Ended,2,0,0,2,0,...,0,2013/04/02 00:00:00+00,At Intersection (intersection related),NaN,N,Clear,Dry,Daylight,NaN,NaN
3,Matched,Block,1,Property Damage Only Collision,Sideswipe,8,0,0,2,0,...,0,2013/03/30 00:00:00+00,Mid-Block (not related to intersection),NaN,N,Clear,Dry,Daylight,NaN,NaN
4,Unmatched,Intersection,0,Unknown,NaN,0,0,0,0,0,...,0,2004/02/15 00:00:00+00,At Intersection (intersection related),NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Check for missing values in the updated dataset

In [10]:
df.head()
missing_data=df.isnull()
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

STATUS
False    221006
Name: STATUS, dtype: int64

ADDRTYPE
False    217295
True       3711
Name: ADDRTYPE, dtype: int64

SEVERITYCODE
False    221005
True          1
Name: SEVERITYCODE, dtype: int64

SEVERITYDESC
False    221006
Name: SEVERITYDESC, dtype: int64

COLLISIONTYPE
False    194678
True      26328
Name: COLLISIONTYPE, dtype: int64

PERSONCOUNT
False    221006
Name: PERSONCOUNT, dtype: int64

PEDCOUNT
False    221006
Name: PEDCOUNT, dtype: int64

PEDCYLCOUNT
False    221006
Name: PEDCYLCOUNT, dtype: int64

VEHCOUNT
False    221006
Name: VEHCOUNT, dtype: int64

INJURIES
False    221006
Name: INJURIES, dtype: int64

SERIOUSINJURIES
False    221006
Name: SERIOUSINJURIES, dtype: int64

FATALITIES
False    221006
Name: FATALITIES, dtype: int64

INCDATE
False    221006
Name: INCDATE, dtype: int64

JUNCTIONTYPE
False    209046
True      11960
Name: JUNCTIONTYPE, dtype: int64

INATTENTIONIND
True     190818
False     30188
Name: INATTENTIONIND, dtype: int64

UNDERINFL
False    194698
True      26308
Name: UNDERINFL, dtype: int64

WEATHER
False    194489
True      26517
Name: WEATHER, dtype: int64

ROADCOND
False    194569
True      26437
Name: ROADCOND, dtype: int64

LIGHTCOND
False    194401
True      26605
Name: LIGHTCOND, dtype: int64

PEDROWNOTGRNT
True     215819
False      5187
Name: PEDROWNOTGRNT, dtype: int64

SPEEDING
True     211106
False      9900
Name: SPEEDING, dtype: int64

### Correcting Data or removing missing rows

In order to correct the dataset we need to look at the dataset for each column and convert the values appropriately

Following Columns are not missing any values and need no correction
1. STATUS
2. SEVERITYDESC
3. PERSONCOUNT
4. PEDCOUNT
5. PEDCYLCOUNT
6. VEHCOUNT
7. INJURIES
8. SERIOUSINJURIES
9. FATALITIES
10. INCDATE

Let's look at ADDRTYPE

In [ ]:
df['ADDRTYPE'].value_counts()

#### Block - 144694, Alley - 873, Intersection - 71728

You can now convert rest of the records to addresstype as Unknown

In [15]:
df['ADDRTYPE'].replace(np.nan, 'Unknown', inplace=True)

Let's now look at another column - SEVERITYCODE <br>
According to the metadata:
A code that corresponds to the severity of the collision: <br>
• 3—fatality <br>
• 2b—serious injury<br>
• 2—injury<br>
• 1—prop damage<br>
• 0—unknown<br>

In [21]:
df.loc[df['SEVERITYCODE'].isnull()]

,STATUS,ADDRTYPE,SEVERITYCODE,SEVERITYDESC,COLLISIONTYPE,PERSONCOUNT,PEDCOUNT,PEDCYLCOUNT,VEHCOUNT,INJURIES,...,FATALITIES,INCDATE,JUNCTIONTYPE,INATTENTIONIND,UNDERINFL,WEATHER,ROADCOND,LIGHTCOND,PEDROWNOTGRNT,SPEEDING
195468,Matched,Intersection,NaN,Unknown,NaN,2,0,1,1,0,...,0,2018/02/14 00:00:00+00,At Intersection (intersection related),NaN,N,Overcast,Wet,Daylight,NaN,NaN

Convert the missing Severity Code based on the description

In [22]:
df['SEVERITYCODE'].replace(np.nan, '0', inplace=True)

Let's look at one more column - INATTENTIONIND <br>
According to the metadata, this attritbue is describer as Whether or not collision was due to inattention. (Y/N)

In [30]:
df['INATTENTIONIND'].isnull().value_counts()

True     190818
False     30188
Name: INATTENTIONIND, dtype: int64

In [31]:
df['INATTENTIONIND'].value_counts()

Y    30188
Name: INATTENTIONIND, dtype: int64

Only values with Y are populated, rest all records are null, so we assume that this must be N

In [32]:
df['INATTENTIONIND'].replace(np.nan, 'N', inplace=True)

#### Similarly, we'll standardize all the missing records

In [33]:
df['SEVERITYCODE'].replace(np.nan, '0', inplace=True)
df['JUNCTIONTYPE'].replace(np.nan, 'Unknown', inplace=True)
df['ADDRTYPE'].replace(np.nan, 'Unknown', inplace=True)
df['COLLISIONTYPE'].replace(np.nan, 'Unknown', inplace=True)
df['INATTENTIONIND'].replace(np.nan, 'N', inplace=True)
df['UNDERINFL'].replace(np.nan, 'N', inplace=True)
df['UNDERINFL'].replace('0', 'N', inplace=True)
df['UNDERINFL'].replace('1', 'Y', inplace=True)
df['WEATHER'].replace(np.nan, 'Unknown', inplace=True)
df['ROADCOND'].replace(np.nan, 'Unknown', inplace=True)
df['LIGHTCOND'].replace(np.nan, 'Unknown', inplace=True)
df['PEDROWNOTGRNT'].replace(np.nan, 'N', inplace=True)
df['SPEEDING'].replace(np.nan,'N',inplace=True)
df['INCDATE'] = pd.to_datetime(df['INCDATE'],format='%Y-%m-%d')

In [34]:
for column in df.columns.values.tolist():
    print(column)
    print (df[column].value_counts())
    print("")

STATUS
Matched      194751
Unmatched     26255
Name: STATUS, dtype: int64

ADDRTYPE
Block           144694
Intersection     71728
Unknown           3711
Alley              873
Name: ADDRTYPE, dtype: int64

SEVERITYCODE
1     137335
2      58628
0      21602
2b      3092
3        349
Name: SEVERITYCODE, dtype: int64

SEVERITYDESC
Property Damage Only Collision    137335
Injury Collision                   58628
Unknown                            21602
Serious Injury Collision            3092
Fatality Collision                   349
Name: SEVERITYDESC, dtype: int64

COLLISIONTYPE
Parked Car    48446
Angles        35444
Rear Ended    34609
Unknown       26328
Other         24512
Sideswipe     18849
Left Turn     14075
Pedestrian     7652
Cycles         5905
Right Turn     3006
Head On        2180
Name: COLLISIONTYPE, dtype: int64

PERSONCOUNT
2     118788
3      36451
0      24995
4      14990
1      13882
5       6776
6       2785
7       1180
8        547
9        227
10       133
11        59
12        35
13        22
14        22
15        11
17        11
16         8
44         6
20         6
25         6
18         6
19         6
22         5
29         4
26         4
23         3
32         3
47         3
27         3
28         3
37         3
34         3
21         2
36         2
31         2
30         2
24         2
35         1
81         1
39         1
41         1
43         1
48         1
53         1
54         1
57         1
93         1
Name: PERSONCOUNT, dtype: int64

PEDCOUNT
0    212948
1      7744
2       274
3        28
4         9
5         2
6         1
Name: PEDCOUNT, dtype: int64

PEDCYLCOUNT
0    215024
1      5931
2        51
Name: PEDCYLCOUNT, dtype: int64

VEHCOUNT
2     149992
1      27809
0      26552
3      13337
4       2513
5        557
6        153
7         53
8         18
9         10
11         6
10         2
15         1
14         1
13         1
12         1
Name: VEHCOUNT, dtype: int64

INJURIES
0     159171
1      47175
2      10669
3       2727
4        813
5        273
6        100
7         40
8         12
9         10
10         6
11         5
13         2
78         1
15         1
12         1
Name: INJURIES, dtype: int64

SERIOUSINJURIES
0     217912
1       2926
2        133
3         23
4          6
5          5
41         1
Name: SERIOUSINJURIES, dtype: int64

FATALITIES
0    220657
1       333
2        12
3         2
5         1
4         1
Name: FATALITIES, dtype: int64

INCDATE
2006-11-02 00:00:00+00:00    103
2004-10-08 00:00:00+00:00     98
2008-10-03 00:00:00+00:00     93
2005-05-18 00:00:00+00:00     89
2004-12-10 00:00:00+00:00     86
2005-11-05 00:00:00+00:00     85
2006-01-13 00:00:00+00:00     85
2008-10-31 00:00:00+00:00     84
2016-10-13 00:00:00+00:00     83
2007-10-19 00:00:00+00:00     81
2005-04-29 00:00:00+00:00     81
2005-04-15 00:00:00+00:00     80
2004-01-02 00:00:00+00:00     80
2004-08-06 00:00:00+00:00     79
2004-11-24 00:00:00+00:00     78
2015-08-14 00:00:00+00:00     78
2004-12-04 00:00:00+00:00     77
2006-06-01 00:00:00+00:00     77
2004-11-01 00:00:00+00:00     76
2006-11-04 00:00:00+00:00     76
2014-10-22 00:00:00+00:00     76
2004-10-05 00:00:00+00:00     75
2004-08-25 00:00:00+00:00     75
2018-06-08 00:00:00+00:00     75
2005-10-28 00:00:00+00:00     75
2007-07-20 00:00:00+00:00     75
2004-12-09 00:00:00+00:00     74
2009-10-16 00:00:00+00:00     74
2007-06-28 00:00:00+00:00     74
2014-11-21 00:00:00+00:00     74
                            ...
2020-03-24 00:00:00+00:00      8
2020-05-31 00:00:00+00:00      8
2020-05-08 00:00:00+00:00      8
2020-05-25 00:00:00+00:00      8
2020-06-21 00:00:00+00:00      8
2020-08-03 00:00:00+00:00      8
2020-04-21 00:00:00+00:00      7
2020-06-06 00:00:00+00:00      7
2020-03-28 00:00:00+00:00      7
2020-07-24 00:00:00+00:00      7
2020-07-11 00:00:00+00:00      7
2020-07-25 00:00:00+00:00      7
2020-03-23 00:00:00+00:00      6
2020-04-05 00:00:00+00:00      6
2020-08-08 00:00:00+00:00      6
2020-08-05 00:00:00+00:00      6
2020-04-28 00:00:00+00:00      6
2020-07-27 00:00:00+00:00      5
2020-08-13 00:00:00+00:00      5
2020-03-31 00:00:00+00:00      4
2020-08-11 00:00:00+00:00      4
2020-04-19 00:00:00+00:00      4
2020-08-10 00:00:00+00:00      4
2020-08-09 00:00:00+00:00      3
2020-08-14 00:00:00+00:00      2
2020-08-17 00:00:00+00:00      2
2020-08-12 00:00:00+00:00      1
2015-12-25 00:00:00+00:00      1
2003-10-06 00:00:00+00:00      1
2020-08-16 00:00:00+00:00      1
Name: INCDATE, Length: 6073, dtype: int64

JUNCTIONTYPE
Mid-Block (not related to intersection)              101441
At Intersection (intersection related)                69022
Mid-Block (but intersection related)                  24385
Unknown                                               11981
Driveway Junction                                     11492
At Intersection (but not related to intersection)      2495
Ramp Junction                                           190
Name: JUNCTIONTYPE, dtype: int64

INATTENTIONIND
N    190818
Y     30188
Name: INATTENTIONIND, dtype: int64

UNDERINFL
N    211377
Y      9629
Name: UNDERINFL, dtype: int64

WEATHER
Clear                       114301
Unknown                      41648
Raining                      34007
Overcast                     28496
Snowing                        919
Other                          851
Fog/Smog/Smoke                 576
Sleet/Hail/Freezing Rain       116
Blowing Sand/Dirt               56
Severe Crosswind                26
Partly Cloudy                    9
Blowing Snow                     1
Name: WEATHER, dtype: int64

ROADCOND
Dry               128101
Wet                48698
Unknown            41566
Ice                 1231
Snow/Slush          1014
Other                136
Standing Water       119
Sand/Mud/Dirt         77
Oil                   64
Name: ROADCOND, dtype: int64

LIGHTCOND
Daylight                    119094
Dark - Street Lights On      50044
Unknown                      40124
Dusk                          6074
Dawn                          2597
Dark - No Street Lights       1573
Dark - Street Lights Off      1236
Other                          244
Dark - Unknown Lighting         20
Name: LIGHTCOND, dtype: int64

PEDROWNOTGRNT
N    215819
Y      5187
Name: PEDROWNOTGRNT, dtype: int64

SPEEDING
N    211106
Y      9900
Name: SPEEDING, dtype: int64

In [35]:
df.head()

,STATUS,ADDRTYPE,SEVERITYCODE,SEVERITYDESC,COLLISIONTYPE,PERSONCOUNT,PEDCOUNT,PEDCYLCOUNT,VEHCOUNT,INJURIES,...,FATALITIES,INCDATE,JUNCTIONTYPE,INATTENTIONIND,UNDERINFL,WEATHER,ROADCOND,LIGHTCOND,PEDROWNOTGRNT,SPEEDING
0,Unmatched,Intersection,2,Injury Collision,Unknown,2,0,0,0,2,...,0,2020-08-10 00:00:00+00:00,At Intersection (intersection related),N,N,Unknown,Unknown,Unknown,N,N
1,Unmatched,Block,2,Injury Collision,Unknown,3,0,0,0,1,...,0,2020-08-14 00:00:00+00:00,Mid-Block (not related to intersection),N,N,Unknown,Unknown,Unknown,N,N
2,Matched,Intersection,1,Property Damage Only Collision,Rear Ended,2,0,0,2,0,...,0,2013-04-02 00:00:00+00:00,At Intersection (intersection related),N,N,Clear,Dry,Daylight,N,N
3,Matched,Block,1,Property Damage Only Collision,Sideswipe,8,0,0,2,0,...,0,2013-03-30 00:00:00+00:00,Mid-Block (not related to intersection),N,N,Clear,Dry,Daylight,N,N
4,Unmatched,Intersection,0,Unknown,Unknown,0,0,0,0,0,...,0,2004-02-15 00:00:00+00:00,At Intersection (intersection related),N,N,Unknown,Unknown,Unknown,N,N

In [38]:
df.groupby(['ADDRTYPE'])['SEVERITYDESC'].value_counts(normalize=True)

ADDRTYPE      SEVERITYDESC
Alley         Property Damage Only Collision    0.772050
              Unknown                           0.128293
              Injury Collision                  0.093929
              Serious Injury Collision          0.005727
Block         Property Damage Only Collision    0.673228
              Injury Collision                  0.209663
              Unknown                           0.105264
              Serious Injury Collision          0.010519
              Fatality Collision                0.001327
Intersection  Property Damage Only Collision    0.522976
              Injury Collision                  0.390615
              Unknown                           0.062444
              Serious Injury Collision          0.021777
              Fatality Collision                0.002189
Unknown       Unknown                           0.479655
              Property Damage Only Collision    0.468068
              Injury Collision                  0.051469
              Serious Injury Collision          0.000808
Name: SEVERITYDESC, dtype: float64

### 77% collisions/accidents in alley results in property damage while ~40% collisions/accidents happening at Intersection results in Injury

In [37]:
df.groupby(['UNDERINFL'])['SEVERITYDESC'].value_counts(normalize=True)

UNDERINFL  SEVERITYDESC
N          Property Damage Only Collision    0.623403
           Injury Collision                  0.260511
           Unknown                           0.102197
           Serious Injury Collision          0.012679
           Fatality Collision                0.001211
Y          Property Damage Only Collision    0.577630
           Injury Collision                  0.369924
           Serious Injury Collision          0.042787
           Fatality Collision                0.009658
Name: SEVERITYDESC, dtype: float64

### 10% more chances of injury in a collision when the driver was under influence of alcohol